application: gdg-nowplaying
version: 2
runtime: go
api_version: go1
threadsafe: yes

handlers:

- url: /styles
  static_dir: dist/styles

- url: /scripts
  static_dir: dist/scripts

- url: /bower_components
  static_dir: dist/bower_components

- url: /font
  static_dir: dist/font

- url: /views
  static_dir: dist/views

- url: /.*
  script: _go_app
